### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by N30Z3N** [AliAssem/MegaNZ-AutoLogin#1]
Sleeping(6)..
[5128:3364:1228/234544.653:ERROR:device_event_log_impl.cc(211)] [23:45:44.594] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[5128:3364:1228/234544.653:ERROR:device_event_log_impl.cc(211)] [23:45:44.655] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "login.py", line 105, in <module>
  File "login.py", line 64, in login
  File "selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
  File "selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[6]/div[2]/div/div[1]/div[1]/div/div[17]/a[2]"}
  (Session info: chrome=87.0.4280.88)

**Comment by AliAssem** [comment]
yes, sorry but I uploaded this as a prototype, but to fix your problem just create a second folder in the main directory and if that doesn't work try collapsing all the folders below it
